FROM alpine:latest
WORKDIR /app
RUN apk update && \
    apk add make && \
    apk add --no-cache python3 python3-dev && \
    apk add python3 py3-pip && \
    pip3 install --upgrade pip
COPY ./tests/ /app/tests/
COPY ./src/ /app/src/
COPY ./Makefile /app/Makefile 
CMD ["make", "run_tests"]