version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./src:/app/src
      - ./Makefile:/app/Makefile
    command: make run_app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./tests:/app/tests
      - ./Makefile:/app/Makefile
    command: make run_tests