
name: hello-world
on: [pull_request, push, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [ '16.x' ]
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Build project'
        run: echo "Make build project"
      - name: "Install node.js"
        run: echo "Install node.js v" ${{ matrix.node-version }}
  tests:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs:    build
    steps:
      - name: 'Run testst'
        run:  echo "Make tests"
  
