
name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Build project'
        run: echo "Make build project"
  tests:
    runs-on:  ubuntu-latest
    steps:
      - name: 'Run testst'
        run:  echo "Make tests"
  
